<?php


namespace api\crm\model;


use think\Model;

class UserAddressModel extends Model
{
    public function userInfo()
    {
        return $this->belongsTo('UserModel', 'user_id');
    }

    //设置默认地址
    public function setDeafaultUser()
    {

    }

    /**
     * 新增地址
     */
    public function addAddress(){

    }

    public function updateData($where)
    {
        return parent::updateData($where); // TODO: Change the autogenerated stub
    }

    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
